export const BEFORE_AUTHENTICATE_USER = 'BEFORE_AUTHENTICATE USER'
export const AFTER_AUTHENTICATE_USER = 'AFTER_AUTHENTICATE_USER'
export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR'

export const BEFORE_SEARCH_BUS = 'BEFORE_SEARCH_BUS'
export const AFTER_SEARCH_BUS = 'AFTER_SEARCH_BUS'
export const SEARCH_BUS_ERROR = 'SEARCH_BUS_ERROR'
export const SEARCH_BUS_RESET = 'SEARCH_BUS_RESET'

export const BEFORE_GET_ALL_LOCATIONS = 'BEFORE_GET_ALL_LOCATIONS'
export const AFTER_GET_ALL_LOCATIONS = 'AFTER_GET_ALL_LOCATIONS'
export const GET_ALL_LOCATION_ERROR = 'GET_ALL_LOCATION_ERROR'

export const BEFORE_POST_INVOICE = 'BEFORE_POST_INVOICE'
export const AFTER_POST_INVOICE = 'AFTER_POST_INVOICE'
export const POST_INVOICE_ERROR = 'POST_INVOICE_ERROR'

export const LOG_OUT = 'LOG_OUT'